#if !canImport(ObjectiveC)
import XCTest

extension PathWranglerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PathWranglerTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PathWranglerTests.__allTests__PathWranglerTests),
    ]
}
#endif
